### ISSUE TITLE
Add option for Google/custom fonts?

### ISSUE THREAD

**Issue by C-Lodder** [C-Lodder/lightning#249]
In two minds whether to add a dropdown of Google fonts, and/or maybe the ability to upload custom fonts.

**Comment by M4dKiwi** [comment]
That would be great, can you please explain a little what the the font awsome (thats actully shi**e) option does?

I had a few issues trying to utillise font awsome but was wondering if there was something affecting the implementation, have also had a few issues around using google fonts
 (I'm aware it may need a popup warning but I'm o.k with the trade off for google fonts convenience over speed &
 I'm sure this may be why it was not part of the original template design)
also I was wondering if we are currently able to have/use  custom  user.js ??.as I'd rather not add code to the original js files .

I think some tradeoffs are worth it for users like myself which is why having such options would be good 
(even if they include a quick note mentioning the trade off - for the unaware)
 - thanks for maintaining & inproving such a great template :)

**Comment by C-Lodder** [comment]
> can you please explain a little what the the font awsome (thats actully shi**e) option does?

Enabling this option will load the [Font Awesome](https://fontawesome.com/) icon library.
If you add `<span class="fas fa-user"></span>` and this option is disabled, nothing will display,

> I'm sure this may be why it was not part of the original template design.

The original template is pretty much just a base. If I added Google Fonts, I'd disable them by default and just let the template use the system fonts.

> Also I was wondering if we are currently able to have/use custom user.js

I do still need to add support for a `custom.js`, just like I did for `custom.css`, however these files wouldn't be required for Google Fonts.....only custom fonts (e.g ones you manually upload)

**Comment by M4dKiwi** [comment]
Thanks for explaining that - it makes it easier now knowing how that works


RE: I do still need to add support for a custom.js, just like I did for
custom.css

(I thought so, but that would be Awsome  - rather than as currently Im
needing to edit the .js files & obviously I'd loose the code on updates)

however these files wouldn't be required for Google Fonts.....only custom
fonts (e.g ones you manually upload)

Yeap ,exactly -  your right .... sorry I was kinda meaning that as a 3rd
separate issue (as a nice to have suggestion)
(I have JS I include into the template code for other things ,but Its not
ideal adding to existing template script each time)

**Comment by C-Lodder** [comment]
done: https://github.com/C-Lodder/lightning/commit/86e7dda0d641c43ec4acf2a3e53ad63c2ae236f1
