### ISSUE TITLE
Ampersands in CSS in version 1.4.2, 1.4.3

### ISSUE THREAD

**Issue by dcsjapan** [C-Lodder/lightning#388]
I'm thinking of using Lightning as a base for a template I need to create, and have been trying to make some modifications to template.css, but csso is choking on some ampersands in the CSS:

```
CssSyntaxError: postcss-csso: /Repositories/tpl_lightning_test/css/template.css:1311:32: Unexpected input

  1309 | }
  1310 | 
> 1311 | .checkbox input[type=checkbox] &:disabled+label,
       |                                ^
  1312 | .checkbox input[type=checkbox] &[aria-disabled]+label,
  1313 | .checkbox input[type=checkbox] &[readonly]+label {
```

There's a few of them in both 1.4.3 and 1.4.2, though 1.4.1 seems to be okay. Haven't checked any earlier versions.

**Comment by C-Lodder** [comment]
Hi @dcsjapan,
You need to process the source CSS through PostCSS (with relevant plugins) before running a minifier. In the compiled CSS, there are no ampersands...only in the source do these exist.
I don't know how you're currently trying to build the CSS, however if you use run the tasks I've showed in the README, it will work: https://github.com/C-Lodder/lightning#build-tasks

You can then modify files in `src/css` rather than editing the `template.css` directly.

**Comment by dcsjapan** [comment]
Thanks for taking the time to respond.

I wasn't using the source; in fact, I had deleted the `/src` directory since I wasn't planning to use it for the quick test site I was putting together.

I was using your installable ZIP (e.g. [this file](https://github.com/C-Lodder/lightning/releases/download/v1.4.3/tpl_lightning-v1.4.3.zip)) and there are indeed ampersands in `/css/template.css`. (I just re-downloaded and checked to be sure.) I'm pretty certain that's supposed to be the compiled CSS, since it's the one `joomla.asset.json` is telling Joomla to use. Please let me know if I'm misunderstanding something.

**Comment by C-Lodder** [comment]
Ahh right, I see them now. My search settings were incorrect.
I'll have a look into this tomorrow.

**Comment by C-Lodder** [comment]
Hi @dcsjapan, I've released an update which fixes the issue: https://github.com/C-Lodder/lightning/releases/tag/v1.4.4

**Comment by dcsjapan** [comment]
Thank you! I'll check it out right away.
